# Profile section
profile:
  first_name: Wilmer
  last_name: Tejada
  picture: static/img/IMG_1821.jpg
  contact:
    address_one: San Jose, CA
    address_two:
    phone: (661)579-5040
  email: wilmer.tejada@yahoo.com
  description:
    - Welcome to my website. I am a Data Analyst and Computer Science student with plenty of experience in SQL, Python, and R.
    - I have also gotten familiar with a some web development which includes Javascript and Flask, which I used to create this website. I am also currently pursuing a second Masters degree in Computer Science with a specialization in Machine Learning. Feel free to visit my LinkedIn/Github in the links below


# Social section
social:
  github: https://github.com/Wilmer-Tejada
  linkedin: https://www.linkedin.com/in/wilmer-tejada/


# Experience section
experience:
  item0:
    position: Research Data Analyst II
    company: San Jose-Evergreen College District
    from: Feb 2019
    to: Present (2 yrs)
    description:
      - Created 10+ Power BI dashboards to track key metrics crucial to evaluating performance including enrollment counts, student success rates, retention rates, awards, etc.
      - Wrote 100+ SQL Server queries, sometimes involving millions of records.
      - Established a Git repository for standardized reports and queries.
      - Served as the liaison between analysts and the database administrators, managing a schema in SQL Server.
      - Fit a logistic regression model, using Python, to determine how a student’s GPA and highest level of high school English affect their chances of succeeding in college level English. This replaced English placement exams and we saw an increase in the number of students succeeding in college English by more than 5%.

  item1:
    position: Research Analyst
    company: Las Positas College
    from: Feb 2017
    to: Feb 2019 (2 yrs)
    description:
      - Reported on college KPI’s using visualizations in R Notebooks/Jupyter.
      - Automated repetitive tasks, including parsing Excel reports and PDF files using Python. This cut down the time for manually inputting records to just a few seconds per file.
      - Saved hundreds of work hours for the Institutional Research department by writing scripts (in R) to automate data tasks such as merging and cleaning data, filtering, visualizations, etc.
      - Helped maintain Tableau dashboards.

  #  item2:
#    position: AI Consultant
#    company: NULLSEC (Startup)
#    from: July 2019
#    to: September 2019
#    description: >
#      Working as an AI consultant for NULLSEC, a computer security company focused on ethical hacking. Particularly helping in the development of NullRansom, an analyzer-debugger software with the purpose of filtering TCP protocol requests, preventing preventively being targeted by malware and ransomware viruses.
#    link: http://www.nullsec.site
  #reference: https://rodolfoferro.xyz/resume/


# Education section
education:
  item1:
    institution: Georgia Institute of Technology
    program: M.S. Computer Science - Machine Learning Specialization
    description:
      - Artificial Intelligence for Robotics
      - Software Architecture & Design
      - Computer Networks
      - Database Systems Concepts & Design
      - Machine Learning for Trading
      - Data and Visual Analytics
      - Deep Learning
      - Machine Learning
    from: January 2019
    to: Present
  item2:
    institution: California State University, East Bay
    program: M.S. Statistics
    description:
      - Probability Theory
      - Statistical Theory
      - Mathematical Statistics I & II
      - Statistical Inference
      - ANOVA Models
      - Regression Models
      - Machine Learning in R
      - Data Visualization
      - R for Data Science
      - SAS Programming
      - Statistical Computing
    from: January 2017
    to: May 2019
  item3:
    institution: University of California, Santa Barbara
    program: B.S. Statistics
    #description:
    from: September 2012
    to: July 2016





# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - r-project
  - git-alt
  - github
extra_skills:
  - SQL Server, MySQL
  - Python – Flask, pandas, NumPy, matplotlib, scikit-learn, etc.
  - R – dplyr, lubridate, ggplot, odbc, etc.
  - Power BI
  - Tableau
  - Web scraping and web automation using Selenium
  - Beginner in Javascript


# Talks and workshops section
#workshops:
#  item0:
#    event: TEDxUNAMLeón
#    workshop: AI in modern times, February 2020.
#    material:
#    link: https://www.ted.com/tedx/events/35293
#  item1:
#    event: PyCon Colombia 2020
#    workshop: 'Workshop – DLaaS: Building cloud-based intelligent solutions, February 2020.'
#    material: https://github.com/RodolfoFerro/PyConCo20
#    link: https://www.pycon.co/ponentes/rodolfo-ferro/
#  item2:
#    event: International Meeting on Artificial Intelligence and its Applications (RIIAA) 2.0.
#    workshop: Workshop – Deep Learning as a Service (DLaaS), August 2019.
#    material: https://github.com/RodolfoFerro/RIIAA19-DLaaS
#    link: https://riiaa.org
#  item3:
#    event: LAB León Web Dev Crash Course 2019.
#    workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019.
#    material: https://github.com/RodolfoFerro/Flask101
#    link: https://flask101.glitch.me
#  item4:
#    event: DevDay León 2019 by Hackademy.
#    workshop: Workshop – (AI) API development with Python, August 2019.
#    material: https://github.com/RodolfoFerro/PythonBaseAPI
#    link:
#  item5:
#    event: Clubes de Ciencia México 2019.
#    workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
#    material: https://rodolfoferro.xyz/hyperspectrum/
#    link:



# Projects section
projects:
  item1:
    title: Embedded Power BI
#    subtitle: Power-BI quick example
    description: A quick mock up of a Power BI dashboard.
    link: powerbi
    github:
    img: powerbi-white.jpeg
    tags: [PowerBI]
  item2:
    title: flask-resume-template
  #    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://github.com/Wilmer-Tejada/Flask-Resume
    github: https://github.com/Wilmer-Tejada/Flask-Resume
    img: website-image.png
    tags: [Flask, Python, Bootstrap]
  item3:
    title: Dashboard Screenshot Examples
#    subtitle: Screenshots of actual production dashboards
    description: Some of these dashboards are currently being used by upper management.
    link: dashboard-screenshots
    github:
    img: power-BI.png
    tags: [Power BI, Data Preprocessing]
  item4:
    title: D3 Examples
    subtitle: D3 Javascript library
    description: Examples of work
    link: d3-examples
    github: https://github.com/Wilmer-Tejada/Javascript-D3-Charts
    img: d3-logo.jpg
    tags: [D3 Javascript]
  item5:
    title: D3 Choropleth
#    subtitle: Google Colab Notebook
    description: A choropleth map created in D3 using a board games csv and countries JSON file.
    link: d3-choropleth
    github: https://github.com/Wilmer-Tejada/Javascript-D3-Charts
    img: choropleth.png
    tags: [D3 Javascript, JSON]
  item6:
    title: Weighted K-Means to Optimize Distribution
    #    subtitle: Google Colab Notebook
    description: A weighted K-Means model to determine optimal distribution centers. Let's user determine clusters. For detailed explanation see Github.
    link: https://wilmer-tejada.shinyapps.io/Kmeans_USCities/
    github: https://github.com/Wilmer-Tejada/Weighted-K-Means-Optimize-U.S.-Distribution
    img: K-Means.png
    tags: [ K-Means, R Shiny, Python ]


# Certifications and awards section
#awards:
#  - 'Winner – #TFWorld TF 2.0 Challenge – TensorFlow at Devpost 2020'
#  - Academy and Technology – Statal Youth Prize Guanajuato 2018
#  - Quantum Computing 101 – IBM Q Certification Badge 2018
#  - 1st. Place – HDI Challenge – Talent City Hackathon 2018
#  - 1st. Place – SWITCH Hackathon 2017
#  - 1st. Place – IBM Hackapalooza – Bluehack Hackathon 2017
#  - 1st. Place – 12th. Creativity and Innovation Contest at the University of Guanajuato 2017
#  - 1st. Place – Centro Fox National Hackathon 2017
#  - 1st. Place – 6th. Creativity and Innovation Contest, DCEA-UG 2016
#  - Silver Award – SynBio Giant Jamboree – iGEM  2016
#  - 1st. Place – 4th. Creativity and Innovation Contest, DCNE-UG 2016
#  - 1st. Place – Fintech – HackBajío Hackathon 2016
