# Profile section
profile:
  first_name: Wilmer
  last_name: Tejada
  picture: static/img/IMG_1821.jpg
  contact:
    address_one: San Jose, CA
    address_two:
    phone: (661)579-5040
  email: wilmer.tejada@yahoo.com
  description:
    - Welcome to my website. Feel free to scroll down to see some of the projects and work that I have done. I am a Data Scientist/Analyst with over 5 years of experience using SQL, Python, and R.
    - I am also currently pursuing a second Masters degree in Computer Science with a specialization in Machine Learning. This led me to build this website, which will host both my past experience and current projects.


# Social section
social:
  github: https://github.com/Wilmer-Tejada
  linkedin: https://www.linkedin.com/in/wilmer-tejada/


# Experience section
experience:
  item0:
    position: Research Data Analyst II
    company: San Jose-Evergreen College District
    from: Feb 2019
    to: Present
    description:
      - Created 10+ Power BI dashboards to track key metrics crucial to evaluating performance including enrollment counts, student success rates, retention rates, awards, etc.
      - Wrote 100+ SQL Server queries, sometimes involving millions of records.
      - Established a Git repository for standardized reports and queries.
      - Served as the liaison between analysts and the database administrators, managing a schema in SQL Server.
      - Fit a logistic regression model, using Python, to determine how a student’s GPA and highest level of high school English affect their chances of succeeding in college level English. This replaced English placement exams and we saw an increase in the number of students succeeding in college English by more than 5%.

  item1:
    position: Research Analyst
    company: Las Positas College
    from: Feb 2017
    to: Feb 2019 (2 yrs)
    description:
      - Reported on college KPI’s using visualizations in R Notebooks/Jupyter.
      - Automated repetitive tasks, including parsing Excel reports and PDF files using Python. This cut down the time for manually inputting records to just a few seconds per file.
      - Saved hundreds of work hours for the Institutional Research department by writing scripts (in R) to automate data tasks such as merging and cleaning data, filtering, visualizations, etc.
      - Helped maintain Tableau dashboards.



# Education section
education:
  item1:
    institution: M.S. Computer Science
    program: Georgia Institute of Technology
    description:
      - Artificial Intelligence for Robotics
      - Software Architecture & Design
      - Computer Networks
      - Database Systems Concepts & Design
      - Machine Learning for Trading
      - Data and Visual Analytics
      - Deep Learning
      - Machine Learning
    from: January 2019
    to: Present
  item2:
    institution: M.S. Statistics
    program: California State University, East Bay
    description:
      - Probability Theory
      - Statistical Theory
      - Mathematical Statistics I & II
      - Statistical Inference
      - ANOVA Models
      - Regression Models
      - Machine Learning in R
      - Data Visualization
      - R for Data Science
      - SAS Programming
      - Statistical Computing
    from: January 2017
    to: May 2019
  item3:
    institution: B.S. Statistics
    program: University of California, Santa Barbara
    #description:
    from: September 2012
    to: July 2016





# Skills section
#tools:
#  # Consider that the following are fa icons:
#  #   https://fontawesome.com/icons?d=gallery&s=brands
#  - python
#  - r-project
#  - git-alt
#  - github
#extra_skills:
#  - SQL Server, MySQL
#  - Python – Flask, pandas, NumPy, matplotlib, scikit-learn, etc.
#  - R – dplyr, lubridate, ggplot, odbc, etc.
#  - Power BI
#  - Tableau
#  - Web scraping and web automation using Selenium
#  - Beginner in Javascript


# Talks and workshops section
#workshops:
#  item0:
#    event:
#    workshop:
#    material:
#    link:



# Projects section
projects:
  item1:
    title: Anomaly Detection using Supervised Machine Learning
    #    subtitle: D3 Javascript library
    description: Cellular Anomaly Detection with XGBoost, Logistic Regression, KNN, Ranodm Forest, Decision Trees.
    link: https://github.com/Wilmer-Tejada/Anomaly-Detection-Using-ML
    github: https://github.com/Wilmer-Tejada/Anomaly-Detection-Using-ML
    img: correlation-matrix.png
    tags: [ Supervised Learning ]

  item2:
    title: Machine Learning to Optimize Distribution Centers
    #    subtitle: Google Colab Notebook
    description: Using weighted K-Means (unsupervised leanring) model to determine optimal distribution centers in the United States. Let's user determine clusters. For detailed explanation see Github.
    link: https://wilmer-tejada.shinyapps.io/Kmeans_USCities/
    github: https://github.com/Wilmer-Tejada/Weighted-K-Means-Optimize-U.S.-Distribution
    img: K-Means.png
    tags: [ Production Model, K-Means, R Shiny, Python ]

  item3:
    title: Python Flask Resume
      #    subtitle: A resume template built with Flask
    description: The code to build this website!
    link: https://github.com/Wilmer-Tejada/Flask-Resume
    github: https://github.com/Wilmer-Tejada/Flask-Resume
    img: website-image.png
    tags: [ Flask, Python, Web Dev, Resume ]

  item4:
    title: Dashboard Screenshots
#    subtitle: Screenshots of actual production dashboards
    description: Examples of past work in Power BI
    link: dashboard-screenshots
    github:
    img: power-BI.png
    tags: [Power BI, Data Preprocessing]

  item5:
    title: Javascript Interactive Visualization
#    subtitle: Google Colab Notebook
    description: A choropleth map created in D3 using a board games csv and countries JSON file.
    link: d3-choropleth
    github: https://github.com/Wilmer-Tejada/Javascript-D3-Charts
    img: choropleth.png
    tags: [D3 Javascript, JSON, Web Dev]
#  item6:
#    title: Embedded Power BI
#  #    subtitle: Power-BI quick example
#      description: A quick mock up of a Power BI dashboard.
#      link: powerbi
#      github:
#      img: powerbi-white.jpeg
#      tags: [PowerBI]
#  item3:
#    title: D3 Examples
#    subtitle: D3 Javascript library
#    description: Examples of work
#    link: d3-examples
#    github: https://github.com/Wilmer-Tejada/Javascript-D3-Charts
#    img: d3-logo.jpg
#    tags: [D3 Javascript]


# Certifications and awards section
#awards:
#  - 'Winner – #TFWorld TF 2.0 Challenge – TensorFlow at Devpost 2020'

